@{
    #### Sitecore SQL Passwords
    SqlCorePassword                         = '#{SqlCorePassword}#'
    SqlSecurityPassword                     = '#{SqlSecurityPassword}#'
    SqlMarketingAutomationPassword          = '#{SqlMarketingAutomationPassword}#'
    SqlMessagingPassword                    = '#{SqlMessagingPassword}#'
    SqlProcessingPoolsPassword              = '#{SqlProcessingPoolsPassword}#'
    SqlCollectionPassword                   = '#{SqlCollectionPassword}#'
    SqlReferenceDataPassword                = '#{SqlReferenceDataPassword}#'
    SqlProcessingEnginePassword             = '#{SqlProcessingEnginePassword}#'
    SqlReportingPassword                    = '#{SqlReportingPassword}#'
    SqlExmMasterPassword                    = '#{SqlExmMasterPassword}#'
    SqlFormsPassword                        = '#{SqlFormsPassword}#'
    SqlMasterPassword                       = '#{SqlMasterPassword}#'
    SqlWebPassword                          = '#{SqlWebPassword}#'
    SqlProcessingTasksPassword              = '#{SqlProcessingTasksPassword}#'
    EXMCryptographicKey                     = '#{EXMCryptographicKey}#'
    EXMAuthenticationKey                    = '#{EXMAuthenticationKey}#'
    
    #### Sitecore Instance Names
    ContentDeliverySiteName                 = 'sc91cd'
    ContentManagementSiteName               = 'sc91cm'
    ReportingSiteName                       = 'sc91rep'
    ProcessingSiteName                      = 'sc91prc'
    ReferenceDateSiteName                   = 'sc91refdata'
    IdentityServerSiteName                  = 'sc91identityserver'
    XP1MarketingAutomationSiteName          = 'sc91ma'
    XP1MarketingAutomationReportingSiteName = 'sc91mareporting'
    XP1ClientCertificateName                = 'sc91xconnect_client'
    XP1CollectionSitename                   = 'sc91collection'
    XP1CollectionSearchSitename             = 'sc91search'
    XP1CortexProcessingSitename             = 'sc91processingEngine'
    XP1CortexReportingSitename              = 'sc91reporting'

    ### Certificates Name
    CollectionCert                          = 'sc91collection'
    CollectionSearchCert                    = 'sc91search'
    ReferenceDataCert                       = 'sc91refdata'
    MarketingAutomationCert                 = 'sc91ma'
    MarketingAutomationReportingCert        = 'sc91mareporting'
    XConnectCert                            = 'sc91xconnect_client'
    CMCert                                  = 'sc91cm'
    CDCert                                  = 'sc91cd'
    CortexProcessingCert                    = 'sc91processingEngine'
    CortexReportingCert                     = 'sc91reporting'
    SitecoreXP1PrcCert                      = 'sc91prc'
    SitecoreXP1RepCert                      = 'sc91rep'
    Solr                                    = 'solr'
    certpassword                            = #{certpassword}#
        
    ### SQL Server Info
    # only two value allowed for sqlType: PaaS or IaaS
    sqlType                                 = '#{sqlType}#'
    sqlServerName                           = 'avasqlsrv007'
    sqlprivateIPAddress                     = '10.0.1.20'
    SqlAdminUser                            = 'sqladmin'
    SqlAdminPassword                        = '#{SqlAdminPassword}#'
    SqlvmAdminPassword                      = '#{SqlvmAdminPassword}#'

    ### Solr Info
    SolrUrl                                 = 'https://solr:8983/solr'
    SolrRoot                                = 'C:\Solr\Solr-7.2.1'
    SolrService                             = 'Solr-7.2.1'
    solrvmName                              = 'solr'
    solrprivateIPAddress                    = '10.0.1.30'
    solrvmScriptScriptFileName              = 'solr.ps1'
    solrVersion                             = '7.2.1'

    ### Sitecore Configs
    Prefix                                  = 'sc91'
    SitecoreAdminPassword                   = 'b'
    SCInstallRoot                           = 'D:\artifacts'
    ClientSecret                            = 'fpnowefwiefnwepifnddecwecw38d3be9fnwefn9efnilweui'
    scSqlIaaS                               = 'https://scartifact001.blob.core.windows.net/sc91/Sitecore%209.1.1rev.002459.zip?st=2019-07-23T09%3A02%3A47Z&se=2020-07-24T09%3A02%3A00Z&sp=rl&sv=2018-03-28&sr=b&sig=81o5M6qgaPpsdjYPFLI2oDGOxMdq1PSvyJdWCzyt1FA%3D'
    scSqlPaaS                               = 'https://scartifact001.blob.core.windows.net/sc91/new-sc.zip?st=2019-08-13T15%3A57%3A18Z&se=2020-08-14T15%3A57%3A00Z&sp=rl&sv=2018-03-28&sr=b&sig=aeJY3FGuohZOXt3c75ajR4FuE%2B8l%2Fgw9kP6I9l8m9us%3D'

    #Infra Parameter
    ResourceGroupLocation                   = '#{ResourceGroupLocation}#'
    ResourceGroupName                       = '#{ResourceGroupName}#'
    cdNodeCount                             = #{cdNodeCount}#
    cdSubnetName                            = 'cd-subnet'
    cmSubnetName                            = 'cm-subnet'
    lbPipName                               = 'lbpip'
    cmSubnetPrefix                          = '10.0.1.0/24'
    VnetPrefix                              = '10.0.0.0/16'
    AdminPassword                           = '#{AdminPassword}#'
    cmvmScriptScriptFileName                = 'cm.ps1'
    cdvmScriptScriptFileName                = 'cd.ps1'
    cdvmName                                = 'cd'
    cmvmName                                = 'cm'
    AdminUsername                           = 'sitecoreadmin'
    cdNSGName                               = 'cd-nsg'
    availabilitySetName                     = 'cd-set'
    cmvmDNSPIP                              = 'testip001dew'
    lbPipDNSName                            = 'javidsclbpip'
    cdSubnetPrefix                          = '10.0.0.0/24'
    cmprivateIPAddress                      = '10.0.1.10'
    cmvmPIP                                 = 'cmpip'
    cdprivateIPAddress                      = '10.0.0.'
    cmNSGName                               = 'cm-nsg'
    vnetName                                = 'vnet'
    cmvmSize                                = 'Standard_F4s'
    loadBalancerName                        = 'sc91'
}